# Renommer ce fichier par constantes.yaml et remplir le mot de passe de la base de données

# Connexion à la base de donnée
DB_:
  HOST: lakartxela
  NAME: apigeon001_pro
  USER: apigeon001_pro
  PASS: apigeon001_pro
PREFIXE_TABLE: dog_