# Renommer ce fichier par constantes.yaml et remplir le mot de passe de la base de données

# Connexion à la base de donnée
DB_:
    HOST: localhost
    NAME: dogsitter
    USER:
    PASS:
PREFIXE_TABLE: dog_

# Paramètres de sécurité
max_connexions_echouees: 3
delai_attente_connexion: 1800 # 30 minutes en secondes
